### ISSUE TITLE
Boto3 client error in multi threaded environment. 

### ISSUE THREAD

**Issue by jnoortheen** [etianen/django-s3-storage#69]
I am using uwsgi behind django in production with threads enabled. I occasionally get 

```
KeyError
'endpoint_resolver'
```
from this line `django_s3_storage/storage.py in _setup at line 140`
```
        if self.settings.AWS_S3_ENDPOINT_URL:
            connection_kwargs["endpoint_url"] = self.settings.AWS_S3_ENDPOINT_URL
        self.s3_connection = boto3.client("s3", config=Config(
            s3={"addressing_style": self.settings.AWS_S3_ADDRESSING_STYLE},
            signature_version=self.settings.AWS_S3_SIGNATURE_VERSION,
        ), **connection_kwargs)
    def _setting_changed_received(self, setting, **kwargs):
        if setting.startswith("AWS_"):
            # HACK: No supported way to close the HTTP session from boto3... :S
            self.s3_connection._endpoint.http_session.close()
````

upon searching I got [this](http://boto3.readthedocs.io/en/latest/guide/resources.html#multithreading-multiprocessing) from boto3 documentation. Is it possible to do the same? like `django-storages` does [here](https://github.com/jschneier/django-storages/pull/358/files).

**Comment by etianen** [comment]
Fixed in 0.12.2

**Comment by jnoortheen** [comment]
Thanks I will check it.

**Comment by jnoortheen** [comment]
The issue is still there. The catch is we need to create new session inside `_Local` class. 

https://github.com/etianen/django-s3-storage/blob/ea2269a1767865b95f00d9eb217dc355af64b64b/django_s3_storage/storage.py#L110

this needs to be changed to 
```
self.session = boto3.session.Session()
self.s3_connection = self.session.client("s3", config=Config(
            s3={"addressing_style": storage.settings.AWS_S3_ADDRESSING_STYLE},
            signature_version=storage.settings.AWS_S3_SIGNATURE_VERSION,
        ), **connection_kwargs)
```

**Comment by etianen** [comment]
I've made your suggested fix to the master branch. Please let me know if it
works. :)

As a general comment on the boto3 library though - what total twaddle is
this?! (I know it's not your library, but I'm venting). Sure... making the
client not thread-safe, I understand that not everything should be
thread-safe. But If I explicitly create a new client in a new thread, why
make it implicitly share a non-thread-safe data structure?! That's the
worst of all worlds!

The boto3 library has been a pain to transition to. All the return values
are untyped dicts. The documentation is all over the place. I don't see how
it can be remotely considered an upgrade from boto2. The only reason to
transition to is was that the boto2 support was being dropped.

**Comment by jnoortheen** [comment]
It works now. Thanks for the quick change :+1:

**Comment by etianen** [comment]
0.12.3 is now released. Thanks for confirming the fix!
